# Generated by Django 6.0.6 on 2026-07-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rule_type', models.CharField(choices=[('percent_off', 'Percent Off'), ('buy_x_get_y', 'Buy X Get Y'), ('bundle_fixed_price', 'Bundle Fixed Price'), ('free_gift', 'Free Gift')], max_length=30)),
                ('config', models.JSONField(help_text='Rule-specific config e.g. {percent: 10} or {buy: 2, get: 1, product_id: 5}')),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
