# Generated by Django 6.0.6 on 2026-07-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discountrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('processing', 'Processing'), ('ready_for_dispatch', 'Ready for Dispatch'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('exchanged', 'Exchanged'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=50),
        ),
    ]
