# Generated by Django 6.0.6 on 2026-07-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('image', models.URLField(max_length=500)),
                ('is_new', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_percentage', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(choices=[('clothing', 'Clothing'), ('cosmetics', 'Cosmetics'), ('other', 'Other')], default='other', max_length=20)),
                ('material_or_ingredients', models.TextField(help_text='Fabric list or ingredient list')),
                ('is_vegan', models.BooleanField(blank=True, null=True)),
                ('is_cruelty_free', models.BooleanField(blank=True, null=True)),
                ('is_hypoallergenic', models.BooleanField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('fit', models.CharField(blank=True, max_length=50, null=True)),
                ('skin_type', models.CharField(blank=True, max_length=50, null=True)),
                ('finish', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('size_color', 'Size & Color'), ('shade_finish_volume', 'Shade, Finish & Volume')], max_length=50)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('shade', models.CharField(blank=True, max_length=100, null=True)),
                ('shade_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sku_suffix', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('image_type', models.CharField(choices=[('primary', 'Primary'), ('angle', 'Angle'), ('swatch', 'Swatch'), ('on_model', 'On Model'), ('user_upload', 'User Upload')], default='angle', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SizeGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('chart_data', models.JSONField(help_text='JSON list of size, chest_in, chest_cm, waist_in, etc.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_guides', to='products.category')),
            ],
        ),
    ]
